"""New migration

Revision ID: 90db1178e628
Revises: 
Create Date: 2023-06-01 16:55:15.855244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90db1178e628'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('user_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'patient', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patient', type_='foreignkey')
    op.drop_column('patient', 'user_id')
    # ### end Alembic commands ###
