"""added treatment column

Revision ID: f892f0de192e
Revises: 90db1178e628
Create Date: 2023-06-03 15:58:20.313313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f892f0de192e'
down_revision = '90db1178e628'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('treatment_in_progress', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'treatment_in_progress')
    # ### end Alembic commands ###
